language: python
python:
    - "3.4"

install:
    - pip install -r devel_requirements.txt

script:
    - python3 setup.py install
    # - python3 setup.py test -a tests/
    - py.test -v

addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN
