language: python
python:
    - "3.4"

install:
    - pip install -r devel_requirements.txt

script:
    - python3 setup.py install
    # - python3 setup.py test -a tests/
    - pytest -v

after_success:
    - coverage xml
    - python-codacy-coverage -r coverage.xml

addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN

notifications:
    email:
        on_success: never
        on_failure: always

